import { test, expect } from '@playwright/test';
import { writeFileSync } from 'node:fs';
test.skip(process.env.CASEPILOT_REAL_ACCEPTANCE !== '1', 'Live model acceptance');
test.use({ viewport: { width: 1600, height: 1100 }, trace: 'on' });
test('new conversation → planning → generate → query → add → modify → delete', async ({ page }, info) => {
  test.setTimeout(1200000); page.setDefaultTimeout(30000);
  const api = `${process.env.CASEPILOT_E2E_API_URL}/api/v1`;
  const records: unknown[] = []; const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  const save = () => writeFileSync(info.outputPath('evidence.json'), JSON.stringify({ records, errors, url: page.url() }, null, 2));
  const shot = async (name: string) => { save(); await page.screenshot({ path: info.outputPath(`${name}.png`), fullPage: true }); };
  await page.addInitScript(() => localStorage.setItem('casepilot.locale.v1', 'zh-CN'));
  await page.goto('/');
  await page.getByLabel('邮箱').fill('demo@casepilot.local');
  await page.getByLabel('密码').fill('CasePilot123!');
  await page.getByRole('button', { name: '登录并进入工作台' }).click();
  await expect(page.getByLabel('写给 CasePilot')).toBeVisible();
  const close = page.getByRole('button', { name: '关闭历史对话' }).last();
  if (await close.isVisible()) await close.click();
  await page.getByLabel('写给 CasePilot').fill('生成2条账号登录测试用例，仅包含以下两个场景：已注册且启用账号输入正确密码登录成功并进入首页；密码错误时提示账号或密码错误且保持未登录。不包含其他功能。');
  await page.getByRole('button', { name: '发送', exact: true }).click();
  const picker = page.locator('.conversation-collection-picker');
  await expect(picker).toBeVisible({ timeout: 180000 });
  await picker.getByPlaceholder('或输入新集合名称').fill(`部署深度验收-${Date.now()}`);
  const binding = page.waitForResponse(r => r.url().endsWith('/confirm-collection') && r.request().method() === 'POST');
  await picker.getByRole('button', { name: '确认并进入工作台' }).click();
  const bound = await (await binding).json();
  records.push({ binding: bound }); save();
  await expect(page.locator('.principle-workbench')).toBeVisible({ timeout: 180000 });
  const boundConversation = await (await page.request.get(`${api}/conversations/${bound.conversation_id}`)).json();
  const collectionId = boundConversation.collection_id;
  const get = async (path: string) => { const r = await page.request.get(`${api}${path}`); expect(r.ok(), await r.text()).toBeTruthy(); return r.json(); };
  const workspace = await get(`/collections/${collectionId}/workspace`);
  const state = () => get(`/conversations/${workspace.id}`);
  const read = () => get(`/collections/${collectionId}/test-cases`);
  const composer = page.locator('.principle-composer textarea');
  async function send(content: string, intent: string) {
    await expect(composer).toBeEnabled({ timeout: 180000 });
    await composer.fill(content);
    const pending = page.waitForResponse(r => /\/(messages|resume)$/.test(new URL(r.url()).pathname) && r.request().method() === 'POST', { timeout: 180000 });
    await page.locator('.principle-composer button[type=submit]').click();
    const r = await pending; expect(r.ok(), await r.text()).toBeTruthy(); const turn = await r.json();
    records.push({ content, turn }); save(); expect(turn.intent).toBe(intent); return turn;
  }
  async function planAndGenerate(label: string) {
    await expect(page.getByRole('region', { name: '测试规划脑图' })).toBeVisible({ timeout: 300000 });
    const before = await read(); const s = await state(); records.push({ label, planning: s.test_briefs.at(-1) });
    expect(s.test_briefs.at(-1).content.planning.test_points.length).toBeGreaterThan(0);
    await shot(`${label}-planning`);
    await page.getByRole('button', { name: '确认规划并生成用例', exact: true }).click();
    await expect(page.getByRole('button', { name: '纳入已选候选', exact: true })).toBeVisible({ timeout: 360000 });
    expect(await read()).toEqual(before);
    const candidates = (await state()).candidates.filter((c: {status: string}) => c.status !== 'committed');
    records.push({ label, candidates }); save();
    await shot(`${label}-candidates`);
    await page.getByRole('button', { name: '纳入已选候选', exact: true }).click();
    await expect.poll(async () => (await read()).length).toBeGreaterThan(before.length);
  }
  expect(await read()).toHaveLength(0);
  await planAndGenerate('01');
  const initial = await read(); expect(initial).toHaveLength(2);
  expect(initial.every((c: {module: string}) => c.module.split('/').length >= 4)).toBeTruthy();
  await send('查询当前集合的所有用例，只查询不修改', 'CASE_QUERY');
  await expect(composer).toBeEnabled({ timeout: 180000 }); expect(await read()).toEqual(initial); await shot('02-query');
  await send('新增1条密码重置用例：重置链接过期后禁止重置密码，并提示重新申请。仅生成这个场景的候选用例。', 'CASE_GENERATE');
  await planAndGenerate('03-add');
  const added = await read(); expect(added).toHaveLength(3);
  const target = added.find((c: {id: string}) => !initial.some((x: {id: string}) => x.id === c.id));
  await send(`仅修改用例 ${target.case_key}：将标题改为「过期重置链接拒绝修改密码」，其他字段保持不变`, 'CASE_MODIFY');
  expect(await read()).toEqual(added);
  await page.reload();
  await page.getByRole('button', { name: '确认修改并生成建议', exact: true }).last().click();
  const review = page.locator('.collection-changes__review');
  await expect(review).toBeVisible({ timeout: 240000 }); expect(await read()).toEqual(added);
  await review.getByRole('button', { name: /一键采纳全部待审阅用例/ }).click();
  await expect.poll(async () => (await read()).find((c: {id: string}) => c.id === target.id)?.title).toBe('过期重置链接拒绝修改密码');
  const modified = await read(); expect(modified.filter((c: {id: string}) => c.id !== target.id)).toEqual(added.filter((c: {id: string}) => c.id !== target.id));
  await shot('04-modified');
  await send(`删除用例 ${target.case_key}，保留其他所有用例`, 'CASE_DELETE');
  expect(await read()).toEqual(modified);
  await page.getByRole('button', { name: '取消变更', exact: true }).click(); expect(await read()).toEqual(modified);
  await send(`删除用例 ${target.case_key}，保留其他所有用例`, 'CASE_DELETE');
  await page.getByRole('button', { name: '确认删除已选用例', exact: true }).click();
  await expect.poll(async () => (await read()).length).toBe(2);
  expect(await read()).toEqual(initial);
  await page.reload(); await expect(composer).toBeEnabled();
  await shot('05-deleted-reloaded'); records.push({ final: await read(), conversation: await state() }); save();
  expect(errors).toEqual([]);
});
