import { expect, test } from '@playwright/test';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
test.skip(process.env.CASEPILOT_REAL_ACCEPTANCE !== '1', 'Live model opt-in');
test.use({ viewport: { width: 1600, height: 1000 }, video: 'on', trace: 'on', actionTimeout: 30000 });
const dir = resolve('../../artifacts/hundred-case-acceptance');
const api = `${process.env.CASEPILOT_E2E_API_URL}/api/v1`;
test('100-case collection query, no match, cancel modification, history and refresh', async ({ page }) => {
  test.setTimeout(600000);
  await page.addInitScript(() => localStorage.setItem('casepilot.locale.v1', 'zh-CN'));
  await page.request.post(`${api}/auth/login`, { data: { email: 'demo@casepilot.local', password: 'CasePilot123!' } });
  const generated = JSON.parse(readFileSync(`${dir}/generated-state.json`, 'utf8'));
  const cid = generated.id; const collectionId = generated.collection_id;
  const initialTaskCount = (await (await page.request.get(`${api}/conversations/${cid}`)).json()).operation_history.length;
  const readCases = async () => (await page.request.get(`${api}/collections/${collectionId}/test-cases`)).json();
  const baseline = await readCases(); expect(baseline).toHaveLength(100);
  const modules = new Map<string, number>();
  for (const item of baseline) modules.set(item.module, (modules.get(item.module) ?? 0) + 1);
  expect(modules.size).toBe(10);
  expect([...modules.values()]).toEqual(Array(10).fill(10));
  const records: unknown[] = [];
  await page.goto(`/workbench/collections/${collectionId}`);
  const composer = page.locator('.principle-composer textarea');
  async function send(content: string) {
    await expect(composer).toBeEnabled(); await composer.fill(content);
    const response = page.waitForResponse(r => r.url().endsWith(`/conversations/${cid}/messages`) && r.request().method() === 'POST');
    await page.locator('.principle-composer button[type=submit]').click();
    const r = await response; expect(r.ok()).toBeTruthy(); const body = await r.json(); records.push({ content, body });
    writeFileSync(`${dir}/followup.json`, JSON.stringify(records, null, 2));
    await expect(composer).toBeEnabled({timeout:180000}); return body;
  }
  const query = await send('查询当前整个集合的全部用例，只查询不修改');
  expect(query.intent).toBe('CASE_QUERY');
  await expect(page.locator('.case-task-detail')).toContainText('100');
  expect(await readCases()).toEqual(baseline);
  await page.screenshot({ path: `${dir}/07-query-hundred.png`, fullPage:true });
  const missing = await send('查询不存在的星际运输模块用例，只查询');
  expect(missing.intent).toBe('CASE_QUERY'); expect(await readCases()).toEqual(baseline);
  await page.screenshot({ path: `${dir}/08-no-matching-module.png`, fullPage:true });
  const changed = await send(`修改用例 ${baseline[0].case_key}：仅将标题改为「验收取消的临时标题」，其他字段保持不变。`);
  expect(changed.intent).toBe('CASE_MODIFY');
  const review = page.locator('.collection-changes__review');
  await expect(review).toContainText('验收取消的临时标题', {timeout:180000});
  expect(await readCases()).toEqual(baseline);
  await page.screenshot({ path: `${dir}/09-change-confirmation.png`, fullPage:true });
  await review.getByRole('button', {name:'取消变更',exact:true}).click();
  expect(await readCases()).toEqual(baseline);
  await page.getByRole('button', {name:'用例工作区',exact:true}).click();
  await expect(page.locator('.case-task-history > button')).toHaveCount(initialTaskCount + 3);
  await page.locator('.case-task-history > button').last().click();
  await expect(page.locator('.task-result-cases')).toContainText('100 条候选用例');
  await page.getByRole('button', {name:'用例脑图',exact:true}).click();
  await expect(page.locator('.react-flow')).toBeVisible();
  await page.screenshot({ path: `${dir}/10-hundred-mind-map.png`, fullPage:true });
  await page.reload(); await expect(composer).toBeEnabled(); expect(await readCases()).toEqual(baseline);
  await page.getByRole('button', {name:'用例工作区',exact:true}).click();
  await expect(page.locator('.case-task-history > button')).toHaveCount(initialTaskCount + 3);
  await page.screenshot({ path: `${dir}/11-history-persisted.png`, fullPage:true });
});

test('a compound request runs two queries in order on the 100-case collection', async ({ page }) => {
  test.setTimeout(180000);
  await page.addInitScript(() => localStorage.setItem('casepilot.locale.v1', 'zh-CN'));
  await page.request.post(`${api}/auth/login`, { data: { email: 'demo@casepilot.local', password: 'CasePilot123!' } });
  const generated = JSON.parse(readFileSync(`${dir}/generated-state.json`, 'utf8'));
  await page.goto(`/workbench/conversations/${generated.id}`);
  const composer = page.locator('.principle-composer textarea'); await expect(composer).toBeEnabled();
  await composer.fill('查询账号登录模块用例，然后查询商品搜索模块用例，只查询不修改');
  await page.locator('.principle-composer button[type=submit]').click();
  let latest: {operation_plan?: {operations: {intent:string;status:string;result:Record<string,unknown>}[]}} = {};
  await expect.poll(async () => {
    latest = await (await page.request.get(`${api}/conversations/${generated.id}`)).json();
    return latest.operation_plan?.operations.map(o => o.status);
  }, {timeout:120000}).toEqual(['completed', 'completed']);
  expect(latest.operation_plan?.operations.map(o => o.intent)).toEqual(['CASE_QUERY','CASE_QUERY']);
  const results = latest.operation_plan!.operations.map(o => o.result.query_cases as {module:string}[]);
  expect(results.map(cases => cases.length)).toEqual([10, 10]);
  expect(results.map(cases => [...new Set(cases.map(c => c.module))])).toEqual([['账号登录'], ['商品搜索']]);
  expect((await (await page.request.get(`${api}/collections/${generated.collection_id}/test-cases`)).json()).length).toBe(100);
  writeFileSync(`${dir}/compound-request.json`, JSON.stringify(latest, null, 2));
  await page.screenshot({path:`${dir}/12-compound-query.png`,fullPage:true});
});
