/* eslint-disable @typescript-eslint/no-explicit-any -- Persisted live acceptance evidence contains heterogeneous API snapshots. */
import {test,expect} from '@playwright/test';
import {mkdirSync,readFileSync,writeFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
test.skip(process.env.CASEPILOT_REAL_ACCEPTANCE!=='1','Real isolated services required');
test.use({actionTimeout:30000,viewport:{width:1600,height:1000},video:{mode:'on',size:{width:1600,height:1000}},trace:'on'});
const dir=resolve('../../output/qa-usability/meeting-thirty');
const api='http://localhost:8101/api/v1';
const prompt='为会议室预约系统生成恰好30条测试用例，分为“预约创建”“预约变更”“签到与释放”三个模块，每个模块恰好10条。先生成候选供我审阅，不直接纳入正式集合。每条包含前置条件、可执行步骤和明确预期。规则：预约时间为每天08:00—20:00，时长30—120分钟，按30分钟递增；最多提前7天预约，人数不得超过会议室容量。同一会议室预约时间不能重叠，前一场结束时间等于后一场开始时间允许预约。只有创建人可修改、取消预约，开始前可以操作，开始后禁止操作。修改失败必须保留原预约。创建人可在开始前10分钟至开始后15分钟内签到，两个边界均包含；超过开始后15分钟仍未签到则自动释放。重复签到不得产生重复记录，释放后可重新预约。覆盖正常流程、边界、权限、冲突和失败后数据保持。仅使用以上规则，不确定的内容先澄清，不自行补充业务规则。';
test('meeting thirty natural language full lifecycle',async({page})=>{
 test.setTimeout(3600000);mkdirSync(dir,{recursive:true});
 const file=`${dir}/journal.json`;const j:any=existsSync(file)?JSON.parse(readFileSync(file,'utf8')):{stages:{},turns:{},observations:[]};
 const save=()=>writeFileSync(file,JSON.stringify(j,null,2));
 const docs:string[]=[];const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.resourceType()==='document'&&r.frame()===page.mainFrame())docs.push(r.url());});
 await page.addInitScript(()=>localStorage.setItem('casepilot.locale.v1','zh-CN'));
 const login=await page.request.post(`${api}/auth/login`,{data:{email:'demo@casepilot.local',password:'CasePilot123!'}});expect(login.ok()).toBeTruthy();const account=await login.json();
 if(!j.collection){const r=await page.request.post(`${api}/spaces/${account.spaces[0].id}/collections`,{data:{name:`QA 会议室30条全流程-${Date.now()}`,description:'全新对话生成30条，部分采纳，整模块换方向改写，多意图和增删查改'}});expect(r.ok()).toBeTruthy();j.collection=await r.json();save();}
 await page.goto(j.conversationId?`/workbench/conversations/${j.conversationId}`:`/workbench/collections/${j.collection.id}`);
 const state=async()=>await(await page.request.get(`${api}/conversations/${j.conversationId}`)).json();
 const formal=async()=>await(await page.request.get(`${api}/collections/${j.collection.id}/test-cases`)).json();
 const input=page.locator('.principle-composer textarea');const notice=page.getByTestId('active-mutation-task-notice');const candidates=page.locator('.task-result-cases');const review=page.locator('.collection-changes__review');
 const shot=async(name:string)=>await page.screenshot({path:`${dir}/${name}.png`,fullPage:true});
 const stage=async(name:string,fn:()=>Promise<void>)=>{if(j.stages[name])return;await test.step(name,fn);j.stages[name]=true;save();};
 const send=async(key:string,content:string)=>{if(j.turns[key])return j.turns[key];await expect(input).toBeEnabled({timeout:600000});await input.fill(content);const response=page.waitForResponse(r=>r.request().method()==='POST'&&/\/(messages|resume)$/.test(new URL(r.url()).pathname),{timeout:180000});await page.locator('.principle-composer button[type=submit]').click();const r=await response;expect(r.ok()).toBeTruthy();j.turns[key]=await r.json();j.conversationId=j.turns[key].conversation_id;save();return j.turns[key];};
 const open=async()=>{await expect(input).toBeEnabled({timeout:600000});await notice.getByRole('button',{name:'前往工作区审阅',exact:true}).click();};
 const ready=async(turn:any)=>{expect(turn.action.change_set_id,JSON.stringify(turn.action)).toBeTruthy();await expect.poll(async()=>{const c=await(await page.request.get(`${api}/case-change-sets/${turn.action.change_set_id}`)).json();if(c.status==='failed'){j.failure=c;save();throw Error(c.error_code??JSON.stringify(c));}return c.status;},{timeout:900000,intervals:[2000,4000]}).toBe('ready');if(turn.intent==='CASE_DELETE'){await expect(input).toBeEnabled({timeout:600000});await page.locator('.principle-viewbar').getByRole('button',{name:'用例工作区',exact:true}).click();}else await open();const c=await(await page.request.get(`${api}/case-change-sets/${turn.action.change_set_id}`)).json();if(turn.intent==='CASE_DELETE')await expect(review).toContainText('删除审阅');else await expect(review).toContainText(`修改方案 V${Math.max(...c.items.map((i:any)=>i.proposal_version??1))}`);return c;};
 const row=(ref:string)=>review.locator('.collection-changes__items > details').filter({has:page.locator('summary').filter({hasText:new RegExp('^'+ref.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+' ·')})});
 const caseRow=async(ref:string)=>{const r=row(ref);if(!await r.evaluate(el=>(el as HTMLDetailsElement).open))await r.locator('summary').click();return r;};
 await stage('01_generate_30',async()=>{await send('generate',prompt);let s=await state();if(s.workflow_runs.some((r:any)=>r.operation==='generate'&&r.status==='failed')){j.observations.push({issue:'generation_failed',runs:s.workflow_runs});save();await page.getByRole('button',{name:'重试本次请求',exact:true}).last().click();await expect.poll(async()=>(await state()).workflow_runs.find((r:any)=>r.operation==='generate')?.status).not.toBe('failed');s=await state();}if(s.candidates.length!==30&&s.context.phase!=='generating'){await expect(page.getByRole('button',{name:'确认范围并生成用例',exact:true})).toBeEnabled({timeout:300000});await page.getByRole('button',{name:'确认范围并生成用例',exact:true}).click();}await expect.poll(async()=>{const s=await state();const failed=s.workflow_runs.find((r:any)=>r.status==='failed');if(failed){j.failure=failed;save();throw Error(failed.error_code);}return s.candidates.length;},{timeout:1200000,intervals:[3000,6000]}).toBe(30);j.generated=await state();expect(await formal()).toHaveLength(0);for(const moduleName of ['预约创建','预约变更','签到与释放'])expect(j.generated.candidates.filter((c:any)=>c.snapshot.module===moduleName)).toHaveLength(10);expect(new Set(j.generated.candidates.map((c:any)=>c.snapshot.title)).size).toBe(30);for(const c of j.generated.candidates){expect(c.snapshot.preconditions.length).toBeGreaterThan(0);expect(c.snapshot.steps.length).toBeGreaterThan(0);for(const s of c.snapshot.steps){expect(s.action.length).toBeGreaterThan(3);expect(s.expected.length).toBeGreaterThan(3);}}await shot('01-generated-30');});
 if(process.env.CASEPILOT_MEETING_PHASE==='generate')return;
 await stage('02_partial_10',async()=>{await open();if((await formal()).length===0){for(const c of (await state()).candidates.filter((c:any)=>c.snapshot.module!=='预约创建')){await candidates.getByRole('checkbox',{name:`纳入 ${c.ref}`,exact:true}).uncheck();await expect(input).toBeEnabled();}await candidates.getByRole('button',{name:'纳入已选候选',exact:true}).click();}await expect.poll(async()=>(await formal()).length).toBe(10);j.firstFormal=await formal();j.remaining=(await state()).candidates;j.root=(await state()).context.active_mutation_task_id;expect(j.remaining).toHaveLength(20);await expect(notice).toBeVisible();await shot('02-partial-ten');});
 await stage('03_query_counts',async()=>{const turn=await send('queryCounts','现在正式用例和待审阅候选各有多少？分别按模块列出来，只查询，不修改。');j.queryState=await state();j.querySummary=j.queryState.messages.filter((m:any)=>m.role==='assistant'&&m.created_at>=turn.user_message.created_at).map((m:any)=>m.content).join('\n');save();expect(j.querySummary).toMatch(/正式[^\n]*10|10[^\n]*正式/);expect(j.querySummary).toMatch(/候选[^\n]*20|20[^\n]*候选/);expect(turn.action.type).not.toBe('task_review_required');expect(j.queryState.context.active_mutation_task_id).toBe(j.root);expect(await formal()).toEqual(j.firstFormal);await shot('03-query-counts');});
 await stage('04_module_rewrite',async()=>{const turn=await send('rewriteModule','整体重写“预约变更”模块的全部10条候选。重点检查修改或取消失败后原预约是否完整保留，把原预约数据、修改或取消请求、失败响应和再次查询原预约拆成可执行步骤；正常成功用例仍验证成功后的数据。保留每条原测试目标和业务规则，其他模块不要动。不是只改标题或优先级。');const c=await ready(turn);j.rewrite1=c;expect(c.items).toHaveLength(10);expect(c.items.every((i:any)=>i.target_type==='candidate'&&i.base_snapshot.module==='预约变更')).toBeTruthy();for(const i of c.items)expect(i.field_diff.some((d:any)=>d.field==='steps')).toBeTruthy();expect(await formal()).toEqual(j.firstFormal);expect((await state()).context.active_mutation_task_id).toBe(j.root);await caseRow(c.items[0].ref);await shot('04-module-ten-diff');});
 await stage('05_change_direction',async()=>{const turn=await send('changeDirection','这版太偏接口了。还是“预约变更”模块这10条候选，改成普通用户通过页面执行的测试：写清进入哪个页面、点击什么、输入什么、看到什么提示，以及回到列表和详情怎样确认原预约没变。不要数据库或接口操作；成功场景应验证新值，失败场景验证原值。保留必要的业务边界、原标题和模块，其他模块不要动。');const c=await ready(turn);j.rewrite2=c;expect(c.items).toHaveLength(10);for(const i of c.items){expect(i.previous_snapshot).toEqual(j.rewrite1.items.find((x:any)=>x.ref===i.ref).proposed_snapshot);expect(i.field_diff.some((d:any)=>d.field==='steps')).toBeTruthy();expect(JSON.stringify(i.proposed_snapshot.steps)).toMatch(/页面|点击|列表|详情/);}expect(await formal()).toEqual(j.firstFormal);expect((await state()).context.active_mutation_task_id).toBe(j.root);await caseRow(c.items[0].ref);await shot('05-ui-direction-diff');});
 await stage('06_accept_three',async()=>{await open();j.acceptedRefs??=j.rewrite2.items.slice(0,3).map((i:any)=>i.ref);save();for(const ref of j.acceptedRefs){const current=await(await page.request.get(`${api}/case-change-sets/${j.rewrite2.id}`)).json();if(current.items.find((i:any)=>i.ref===ref).status==='applied')continue;const r=await caseRow(ref);await r.getByRole('button',{name:'采纳此用例',exact:true}).click();await expect(input).toBeEnabled();}j.afterThree=await state();expect(await formal()).toEqual(j.firstFormal);await expect(review).toContainText('待审阅 7 条');await shot('06-three-accepted-seven-pending');});
 await stage('07_refine_seven',async()=>{const turn=await send('refineSeven','“预约变更”模块剩余7条未采纳建议的候选，预期还不够具体。请明确预约时间、会议室和人数在列表与详情中应显示什么。沿用每条场景的测试数据，未给出的数据可设置为满足既有规则的具体测试数据。刚刚采纳的3条不要再改，其他模块不要动。');const c=await ready(turn);j.rewrite3=c;expect(c.items.filter((i:any)=>i.status==='applied')).toHaveLength(3);expect(c.items.filter((i:any)=>!['applied','rejected'].includes(i.status))).toHaveLength(7);const s=await state();for(const ref of j.acceptedRefs)expect(s.candidates.find((x:any)=>x.ref===ref)).toEqual(j.afterThree.candidates.find((x:any)=>x.ref===ref));expect(await formal()).toEqual(j.firstFormal);await shot('07-refined-seven');});
 await stage('08_discard_and_retry',async()=>{await open();j.discardRef??=j.rewrite3.items.find((i:any)=>i.status!=='applied').ref;save();if(!j.discarded){const r=await caseRow(j.discardRef);await r.getByRole('button',{name:'丢弃此建议',exact:true}).click();await expect(input).toBeEnabled();j.discarded=await state();save();}const turn=await send('retryDiscard',`重新修改刚才丢弃建议的候选 ${j.discardRef}，保留原测试目标与业务规则，把页面操作步骤写完整，并在预期明确预约时间、会议室与人数。只修改这条，不动已采纳的3条，保留其他6条待审阅建议。`);const c=await ready(turn);j.rewrite4=c;expect(c.items.find((i:any)=>i.ref===j.discardRef).status).not.toBe('rejected');expect(c.items.filter((i:any)=>i.status==='applied')).toHaveLength(3);for(const i of j.rewrite3.items.filter((i:any)=>i.ref!==j.discardRef))expect(c.items.find((x:any)=>x.ref===i.ref).proposed_snapshot).toEqual(i.proposed_snapshot);expect(await formal()).toEqual(j.firstFormal);await shot('08-discard-then-rewrite');});
 await stage('09_finish_thirty',async()=>{await open();if(!j.allSuggestionsAccepted){await review.getByRole('button',{name:'一键采纳全部待审阅用例（7 条）',exact:true}).click();await expect(input).toBeEnabled();j.allSuggestionsAccepted=await state();save();}if((await formal()).length<30){for(const c of (await state()).candidates){await candidates.getByRole('checkbox',{name:`纳入 ${c.ref}`,exact:true}).check();await expect(input).toBeEnabled();}await candidates.getByRole('button',{name:'纳入已选候选',exact:true}).click();}await expect.poll(async()=>(await formal()).length).toBe(30);j.thirty=await formal();const s=await state();expect(s.context.active_mutation_task_id).toBeNull();for(const original of j.firstFormal)expect(j.thirty.find((c:any)=>c.id===original.id)).toEqual(original);for(const c of j.allSuggestionsAccepted.candidates){const f=j.thirty.find((x:any)=>x.title===c.snapshot.title);expect(f).toBeTruthy();expect(f.preconditions).toEqual(c.snapshot.preconditions);expect(f.steps.map(({action,expected}:any)=>({action,expected}))).toEqual(c.snapshot.steps.map(({action,expected}:any)=>({action,expected})));}await shot('09-thirty-formal');});
 if(process.env.CASEPILOT_MEETING_PHASE==='rewrite')return;

 await stage('10_add_five',async()=>{await send('addFive','新增“预约查询”模块，生成恰好5条候选用例，每个场景1条：查看本人预约列表、按日期筛选、查看预约详情、无结果展示、取消后状态展示。只能查看本人预约。每条有明确前置条件、页面操作步骤和预期，先供我审阅，不直接纳入正式集合，现有30条用例不变。');const s=await state();if(s.candidates.length!==5&&s.context.phase!=='generating'){await expect(page.getByRole('button',{name:'确认范围并生成用例',exact:true})).toBeEnabled({timeout:300000});await page.getByRole('button',{name:'确认范围并生成用例',exact:true}).click();}await expect.poll(async()=>{const s=await state();const failed=s.workflow_runs.filter((r:any)=>r.operation==='generate'&&r.status==='failed').at(-1);if(failed)throw Error(failed.error_code);return s.candidates.length;},{timeout:900000,intervals:[2000,4000]}).toBe(5);j.addedState=await state();expect(j.addedState.context.active_mutation_task_id).not.toBe(j.root);expect(j.addedState.candidates.every((c:any)=>c.snapshot.module==='预约查询')).toBeTruthy();expect(await formal()).toEqual(j.thirty);await shot('10-five-new-candidates');});
 await stage('11_gate_delete',async()=>{const before=await state();const t=await send('blockedDelete','先删除“预约查询”模块吧。');expect(t.action.type).toBe('task_review_required');expect(t.assistant_message.content).toContain('采纳或放弃');const after=await state();expect(after.operation_history.length).toBe(before.operation_history.length);expect(after.context.active_mutation_task_id).toBe(j.addedState.context.active_mutation_task_id);expect(await formal()).toEqual(j.thirty);await open();await expect(candidates.locator(':scope > details')).toHaveCount(5);await shot('11-dialogue-review-gate');});
 await stage('12_adopt_five',async()=>{await open();if((await formal()).length<35){await candidates.getByRole('button',{name:'纳入已选候选',exact:true}).click();}await expect.poll(async()=>(await formal()).length).toBe(35);j.thirtyFive=await formal();expect((await state()).context.active_mutation_task_id).toBeNull();for(const c of j.thirty)expect(j.thirtyFive.find((x:any)=>x.id===c.id)).toEqual(c);await shot('12-thirty-five-formal');});
 await stage('13_query_two',async()=>{const t=await send('queryTwo','查询“预约查询”模块中关于无结果展示和取消后状态展示的用例，只列出来，不修改。');expect(t.intent).toBe('CASE_QUERY');const s=await state();const op=s.operation_history.filter((o:any)=>o.intent==='CASE_QUERY').at(-1);j.deleteTargets=op.result.query_cases;expect(j.deleteTargets).toHaveLength(2);expect(j.deleteTargets.every((c:any)=>c.module==='预约查询')).toBeTruthy();await shot('13-query-two');});
 await stage('14_cancel_delete',async()=>{const t=await send('deleteFirst','删除刚才查询到的两条用例，其他用例不动。');const c=await ready(t);expect(c.items).toHaveLength(2);expect(new Set(c.items.map((i:any)=>i.ref))).toEqual(new Set(j.deleteTargets.map((x:any)=>x.id)));expect(await formal()).toEqual(j.thirtyFive);await shot('14-delete-before-confirmation');await review.getByRole('button',{name:'取消变更',exact:true}).click();await expect(input).toBeEnabled();expect(await formal()).toEqual(j.thirtyFive);expect((await state()).context.active_mutation_task_id).toBeNull();await shot('15-delete-cancelled');});
 await stage('15_confirm_delete',async()=>{const t=await send('deleteAgain',`删除用例 ${j.deleteTargets.map((c:any)=>c.case_key).join('、')}，其他用例不动。`);const c=await ready(t);expect(c.items).toHaveLength(2);expect(await formal()).toEqual(j.thirtyFive);await review.getByRole('button',{name:'确认删除已选用例',exact:true}).click();await expect.poll(async()=>(await formal()).length).toBe(33);j.finalCases=await formal();for(const f of j.finalCases)expect(f).toEqual(j.thirtyFive.find((x:any)=>x.id===f.id));expect((await state()).context.active_mutation_task_id).toBeNull();await shot('16-delete-confirmed-33');});
 await stage('16_summary',async()=>{const t=await send('finalSummary','汇总当前各模块用例数量，以及本次新增、改写和删除的结果，只查询汇总，不修改。');j.summary=t;const counts:Record<string,number>={};for(const c of await formal())counts[c.module]=(counts[c.module]??0)+1;expect(counts).toEqual({'预约创建':10,'预约变更':10,'签到与释放':10,'预约查询':3});j.finalCounts=counts;expect(t.assistant_message.content).toContain('33');expect(t.assistant_message.content).toContain('预约查询 3 条');expect(t.assistant_message.content).toContain('累计纳入 35 条');expect(t.assistant_message.content).toContain('改写涉及 10 条');expect(t.assistant_message.content).toContain('删除 2 条');await shot('17-final-summary');});
 j.passed=true;

 j.lastState=await state();j.lastFormal=await formal();j.browser={documents:docs,errors};save();expect(errors).toEqual([]);expect(docs).toHaveLength(1);
});
